
name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/571750093829/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'firebase-deployer@etqan-6973c.iam.gserviceaccount.com'

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: 'firebase-deployer@etqan-6973c.iam.gserviceaccount.com'
          channelId: live
          projectId: etqan-6973c
